### ISSUE TITLE
로그인 event handler

### ISSUE THREAD

**Issue by tkdgus1030** [tkdgus1030/OSS_project#12]
![image](https://user-images.githubusercontent.com/63357094/143768819-8a7ce394-8571-460b-8f38-44618407f25c.png)
로그인 버튼이 위와같이 onclick attribute가 설정되어 있어서
올바르지 않은 휴대폰 번호와 비밀번호를 입력해도 무조건 페이지가 넘어갑니다.
수정해야 할 것 같습니다.

**Comment by tkdgus1030** [comment]
수정완료 했습니다.

**Comment by theran23** [comment]
확인했습니다 
Function으로 넘어가도록 수정했습니다
